# Continuous Hosting with Auto-Restart
#
# Runs your container 24/7 on GitHub Actions with:
# - Automatic container/tunnel restart if crashed
# - Graceful handoff before 6-hour job timeout
#
# Requirements:
# - Cloudflare Tunnel configured (see README)
# - Secrets: CF_TUNNEL_TOKEN, WORKFLOW_PAT (repo scope)
# - Variables: APP_URL
# - Pre-built image in GHCR (or use dockerfile input)
#
# Copy to .github/workflows/deploy.yml

name: Deploy

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [restart-deploy]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 350
    permissions:
      actions: write
      packages: read

    steps:
      - name: Cancel previous run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PREV=$(gh api repos/${{ github.repository }}/actions/workflows/deploy.yml/runs \
            --jq ".workflow_runs[] | select(.id < ${{ github.run_id }} and .status == \"in_progress\") | .id" \
            | head -1)
          if [ -n "$PREV" ]; then
            gh api repos/${{ github.repository }}/actions/runs/$PREV/cancel -X POST
            echo "Graceful handoff: waiting 60s"
            sleep 60
          fi

      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: jonasneves/serverless-infra/.github/actions/expose-service@main
        id: expose
        with:
          image: ghcr.io/${{ github.repository }}:latest
          port: 3000
          tunnel_token: ${{ secrets.CF_TUNNEL_TOKEN }}
          tunnel_url: ${{ vars.APP_URL }}
          health_check: /health
          keep_alive: true
          duration: '5.5'

      - name: Trigger restart
        if: always()
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_PAT }}
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            -f event_type=restart-deploy
